# Generated by Django 2.1.4 on 2020-01-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200129_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebook',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
